# Numpy

### Importing

In [2]:
import numpy as np
np.__version__

'1.16.1'

### Creating a new numpy array

Creating an ininstantiated array.

In [3]:
np.empty((2, 3))

array([[-2.68156159e+154, -2.68156159e+154,  6.94961698e-310],
       [ 6.94961698e-310, -2.68156159e+154,  4.21544859e-309]])

Creating an array instantiated with a constant value.

In [4]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((2, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [6]:
np.full((2, 3), 4.0)

array([[4., 4., 4.],
       [4., 4., 4.]])

Creating an array using arange.

In [7]:
np.arange(3, 6)

array([3, 4, 5])

In [8]:
np.arange(0, 6, 2)

array([0, 2, 4])

In [9]:
np.arange(4, 5, 0.1)

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

Creating an array with linspace and logspace.

In [10]:
np.linspace(1.2, 1.8, 6)

array([1.2 , 1.32, 1.44, 1.56, 1.68, 1.8 ])

In [37]:
np.logspace(1, 3, 5)

array([  10.        ,   31.6227766 ,  100.        ,  316.22776602,
       1000.        ])

Converting an array from python lists or tuples.

In [12]:
np.array([1, 2, 3])

array([1, 2, 3])

In [13]:
np.array([[1, 2, 3],[4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np.array([(1, 2, 3),(4, 5, 6)])

array([[1, 2, 3],
       [4, 5, 6]])

Copying an existing numpy array (deep copy).

In [15]:
x = np.array((1, 2, 3))
y = np.copy(x)
y

array([1, 2, 3])

### Element access

In [16]:
# to use in the examples
x = np.arange(10)
x[3]

3

### Change the shape of an array

In [17]:
x = np.arange(10)
x.shape

(10,)

In [18]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Flattening an array.

In [19]:
# returns a deep copy
y = np.array([[1, 2, 3],[4, 5, 6]])
y.flatten()

array([1, 2, 3, 4, 5, 6])

In [20]:
# returns a shallow copy
y.ravel()

array([1, 2, 3, 4, 5, 6])

Transpose of an array.

In [21]:
y.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### Joining and splitting arrays

In [22]:
x = np.array([[1, 2, 3],[4, 5, 6]])
y = np.array([[7, 8, 9]])
np.concatenate((x, y), axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
z = np.array([[10, 11]]).T
np.concatenate((x, z), axis=1)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11]])

In [24]:
x = np.arange(10)
np.split(x, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [25]:
np.split(x, [5, 7, 10])

[array([0, 1, 2, 3, 4]),
 array([5, 6]),
 array([7, 8, 9]),
 array([], dtype=int64)]

### Inserting and removing elements

Inserting an element into an array.

In [26]:
x = np.arange(4)
np.insert(x, 1, 8)

array([0, 8, 1, 2, 3])

In [27]:
x = np.array([[1, 2], [3, 4]])
np.insert(x, 0, [8, 9], axis=0)

array([[8, 9],
       [1, 2],
       [3, 4]])

In [28]:
np.append(x, [[8, 9]], axis=0)

array([[1, 2],
       [3, 4],
       [8, 9]])

Deleting an element from an array.

In [29]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.delete(x, 1, 0)

array([[1, 2, 3],
       [7, 8, 9]])

In [30]:
np.delete(x, [0, 1])

array([3, 4, 5, 6, 7, 8, 9])

Returning the unique elements of an array.

In [31]:
x = np.array([3, 2, 6, 2, 1, 3, 1, 2, 6, 3])
np.unique(x)

array([1, 2, 3, 6])

### Bitwise operations

In [32]:
x = np.array([False, False, True, True])
y = np.array([False, True, False, True])

In [33]:
np.bitwise_and(x, y)

array([False, False, False,  True])

In [34]:
np.bitwise_or(x, y)

array([False,  True,  True,  True])

In [35]:
np.bitwise_xor(x, y)

array([False,  True,  True, False])

In [36]:
np.invert(x)

array([ True,  True, False, False])