# Numpy

### Importing

In [1]:
import numpy as np
np.__version__

'1.14.0'

### Creating a new numpy array

Creating an ininstantiated array.

In [2]:
np.empty((2, 3))

array([[-2.31584178e+077, -1.49457771e-154,  2.15537863e-314],
       [ 2.15540364e-314,  2.15541371e-314,  2.15538906e-314]])

Creating an array instantiated with a constant value.

In [3]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones((2, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [5]:
np.full((2, 3), 4.0)

array([[4., 4., 4.],
       [4., 4., 4.]])

Creating an array using arange.

In [6]:
np.arange(3, 6)

array([3, 4, 5])

In [7]:
np.arange(0, 6, 2)

array([0, 2, 4])

In [8]:
np.arange(4, 5, 0.1)

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

Creating an array with linspace.

In [9]:
np.linspace(1.2, 1.8, 6)

array([1.2 , 1.32, 1.44, 1.56, 1.68, 1.8 ])

Converting an array from python lists or tuples.

In [10]:
np.array([1, 2, 3])

array([1, 2, 3])

In [11]:
np.array([[1, 2, 3],[4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.array([(1, 2, 3),(4, 5, 6)])

array([[1, 2, 3],
       [4, 5, 6]])

Copying an existing numpy array (deep copy).

In [13]:
x = np.array((1, 2, 3))
y = np.copy(x)
y

array([1, 2, 3])

### Element access

In [79]:
# to use in the examples
x = np.arange(10)
x[3]

3

### Change the shape of an array

In [35]:
x = np.arange(10)
x.shape

(10,)

In [36]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Flattening an array.

In [37]:
# returns a deep copy
y = np.array([[1, 2, 3],[4, 5, 6]])
y.flatten()

array([1, 2, 3, 4, 5, 6])

In [39]:
# returns a shallow copy
y.ravel()

array([1, 2, 3, 4, 5, 6])

Transpose of an array.

In [23]:
y.T

array([[7],
       [8],
       [9]])

### Joining and splitting arrays

In [26]:
x = np.array([[1, 2, 3],[4, 5, 6]])
y = np.array([[7, 8, 9]])
np.concatenate((x, y), axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
z = np.array([[10, 11]]).T
np.concatenate((x, z), axis=1)

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11]])

In [29]:
x = np.arange(10)
np.split(x, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [33]:
np.split(x, [5, 7, 10])

[array([0, 1, 2, 3, 4]),
 array([5, 6]),
 array([7, 8, 9]),
 array([], dtype=int64)]

### Inserting and removing elements

Inserting an element into an array.

In [68]:
x = np.arange(4)
np.insert(x, 1, 8)

array([0, 8, 1, 2, 3])

In [70]:
x = np.array([[1, 2], [3, 4]])
np.insert(x, 0, [8, 9], axis=0)

array([[8, 9],
       [1, 2],
       [3, 4]])

In [71]:
np.append(x, [[8, 9]], axis=0)

array([[1, 2],
       [3, 4],
       [8, 9]])

Deleting an element from an array.

In [72]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.delete(x, 1, 0)

array([[1, 2, 3],
       [7, 8, 9]])

In [74]:
np.delete(x, [0, 1])

array([3, 4, 5, 6, 7, 8, 9])

Returning the unique elements of an array.

In [78]:
x = np.array([3, 2, 6, 2, 1, 3, 1, 2, 6, 3])
np.unique(x)

array([1, 2, 3, 6])

### Bitwise operations

In [90]:
x = np.array([False, False, True, True])
y = np.array([False, True, False, True])

In [91]:
np.bitwise_and(x, y)

array([False, False, False,  True])

In [92]:
np.bitwise_or(x, y)

array([False,  True,  True,  True])

In [93]:
np.bitwise_xor(x, y)

array([False,  True,  True, False])

In [95]:
np.invert(x)

array([ True,  True, False, False])